---
language: minimal
before_install:
  - sudo apt-get install -y ruby make linkchecker
install: gem install asciidoctor
script:
  - cd guides
  - make clean html BUILD=satellite
  - make clean html linkchecker BUILD=foreman