---
name: Cherry pick to stable branches

on:
  pull_request:
    types:
      - closed

jobs:
  branches:
    name: Determine branches
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.parse.outputs.versions }}
    steps:
      - name: Parse PR message
        id: parse
        if: ${{ github.event.pull_request.merged }}
        run: |
          awk '/^\* \[x\] Foreman [0-9]+\.[0-9]+$/ { print $4 }' <<EOF | python3 -c 'import json, sys ; print(f"::set-output versions={json.dumps(sys.stdin.read().split())}")'
          ${{ github.event.pull_request.body }}
          EOF

  pick:
    name: Create PR
    runs-on: ubuntu-latest
    needs: branches
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.branches.outputs.versions) }}
    steps:
      - name: Checkout ${{ matrix.version }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.version }}
      - run: git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }}
      - name: Open a PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[${{ matrix.version }}] ${{ github.event.pull_request.title }}"
          branch: ${{ matrix.version }}
          body: 'Automated cherry pick of ${{ github.event.pull_request.html_url }} for the ${{ matrix.version }} branch'
          delete-branch: true
