name: preview

on:
  workflow_run:
    workflows:
      - deploy
    types:
      - completed

jobs:
  preview-failed:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download metadata artifact
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs, artifact_name: 'pr'});

      - name: Unzip artifact
        run: unzip pr.zip

      - name: Read PR data
        run: echo "PR_DATA=$(cat ./pr.json)" >> $GITHUB_ENV

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ fromJSON(env.PR_DATA).pr_number }}
          message: "The PR preview for ${{ fromJSON(env.PR_DATA).head_sha }} could not be generated"

  preview:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download metadata artifact
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs, artifact_name: 'pr'});

      - name: Unzip artifact
        run: unzip pr.zip

      - name: Read PR data
        run: echo "PR_DATA=$(cat ./pr.json)" >> $GITHUB_ENV

      - name: Download other artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs, artifact_name: 'foreman-docs-html-${{ fromJSON(env.PR_DATA).branch_name }}'});
            await script({github, context, core, fs, artifact_name: 'foreman-docs-html-base'});
            await script({github, context, core, fs, artifact_name: 'foreman-docs-web-master'});

      - name: Set preview domain
        run: echo "PREVIEW_DOMAIN=$(echo ${{ github.repository }} | tr / - )-${{ github.job }}-pr-${{ fromJSON(env.PR_DATA).pr_number }}.surge.sh" >> $GITHUB_ENV

      - name: Install surge
        run: npm install surge

      - name: Install diffstat
        run: |
          sudo apt-get update
          sudo apt-get install -y diffstat

      - name: Create preview layout
        run: |
          mkdir -p preview/${{ fromJSON(env.PR_DATA).target_name }}
          unzip -d preview foreman-docs-web-master.zip
          unzip -d preview/${{ fromJSON(env.PR_DATA).target_name }} foreman-docs-html-${{ fromJSON(env.PR_DATA).branch_name }}.zip

      - name: Create diff to old base
        run: |
          mkdir old
          unzip -d old foreman-docs-html-base.zip
          diff -Nrwu old/ preview/${{ fromJSON(env.PR_DATA).target_name }}/ | cat > preview/diff.patch
          diffstat -l -p2 preview/diff.patch > diff.txt

      - name: Deploy to surge.sh
        run: ./node_modules/.bin/surge ./preview $PREVIEW_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Generate summary
        run: |
          echo "The PR preview for ${{ fromJSON(env.PR_DATA).head_sha }} is available at [${{ env.PREVIEW_DOMAIN }}](https://${{ env.PREVIEW_DOMAIN }})" >> pr.md
          echo "" >> pr.md
          echo "The following output files are affected by this PR:" >> pr.md
          sed -E "s#(.*)#- [\1](https://${{ env.PREVIEW_DOMAIN }}/${{ fromJSON(env.PR_DATA).target_name }}/\1)#" diff.txt >> pr.md
          echo "" >> pr.md
          echo '[show diff](https://${{ env.PREVIEW_DOMAIN }}/diff.patch)' >> pr.md

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ fromJSON(env.PR_DATA).pr_number }}
          path: pr.md
