---
name: Unused modules
on:
  pull_request:
    paths:
      - 'guides/**.adoc'
      - '.github/workflows/unused.yml'

jobs:
  vale:
    name: Unused modules
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Find unused modules
        run: ./guides/scripts/find_unused_modules
